import { env as cloudflareEnv } from "cloudflare:workers";

/**
 * Typed access to the environment.
 *
 * `worker-configuration.d.ts` is generated by `wrangler types` from
 * `wrangler.jsonc` **and from whatever happens to be in the developer's local
 * `.dev.vars`**. Secrets are therefore not reliably present in the generated
 * `Env` type across machines, which is why this module owns one narrow cast
 * instead of sprinkling `as any` at each read site.
 *
 * Nothing here reads a value at module scope — `env` is only captured, never
 * dereferenced, so importing this module is safe outside a request.
 */
type AppSecrets = {
  /** Signs the session cookie. rwsdk falls back to a dev key under `vite dev`. */
  AUTH_SECRET_KEY?: string;
  /**
   * Supabase Postgres, via the SUPAVISOR POOLER (…pooler.supabase.com:6543).
   *
   * NOT the direct connection: `db.<ref>.supabase.co:5432` resolves to IPv6
   * only, and Cloudflare Workers cannot open outbound IPv6 connections.
   */
  DATABASE_URL?: string;
  /** Supabase project URL, e.g. https://abcd.supabase.co */
  SUPABASE_URL?: string;
  /** Supabase anon/public key. Used for password verification + reset email. */
  SUPABASE_ANON_KEY?: string;
  /** !! SERVICE ROLE !! Provisioning only. Never reaches a browser. */
  SUPABASE_SERVICE_ROLE_KEY?: string;
  /** Absolute public origin, used to build the password-reset redirect link. */
  APP_URL?: string;
  /** Sentry DSN. Optional; error reporting is disabled when unset. */
  SENTRY_DSN?: string;
};

export type AppEnv = Env & AppSecrets;

export const appEnv = cloudflareEnv as unknown as AppEnv;

export type SecretName = keyof AppSecrets;

const WHERE_TO_PUT_IT = (name: string) =>
  `  Local:      add ${name}=... to .dev.vars (see .env.example and SUPABASE_SETUP.md)\n` +
  `  Production: npx wrangler secret put ${name}`;

/**
 * Read a required secret, or fail with a message that says exactly what to do.
 *
 * Missing configuration must never surface as `undefined` propagating into a
 * fetch call and blowing up somewhere unrelated.
 */
export function requireSecret(name: SecretName): string {
  const value = appEnv[name];

  if (!value) {
    throw new Error(
      `${name} is not set.\n${WHERE_TO_PUT_IT(name)}\n` +
        `  Supabase keys are in the dashboard under Project Settings -> API.`,
    );
  }

  return value;
}

/** Optional secret, normalised so `""` reads as absent. */
export function optionalSecret(name: SecretName): string | undefined {
  const value = appEnv[name];
  return value ? value : undefined;
}
