/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f5bb2ad0fc8abeefdcf2bbba3f31b633)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	APP_NAME: "Class Kudos";
	AUTH_SECRET_KEY: string;
	SENTRY_DSN: string;
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	DATABASE: DurableObjectNamespace<import("./src/worker").Database>;
	SESSION_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "Database" | "SessionDurableObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_NAME" | "AUTH_SECRET_KEY" | "SENTRY_DSN" | "SUPABASE_URL" | "SUPABASE_ANON_KEY" | "SUPABASE_SERVICE_ROLE_KEY">> {}
}
