/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 84e3bc3d0cf4a2b7db11aeff2c914d0b)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	APP_NAME: "Class Kudos";
	AUTH_SECRET_KEY: string;
	DATABASE_URL: string;
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	APP_URL: string;
	SESSION_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "SessionDurableObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_NAME" | "AUTH_SECRET_KEY" | "DATABASE_URL" | "SUPABASE_URL" | "SUPABASE_ANON_KEY" | "SUPABASE_SERVICE_ROLE_KEY" | "APP_URL">> {}
}
